### ISSUE TITLE
DOESNOT WORK FOR LIWC2015

### ISSUE THREAD

**Issue by myrainbowandsky** [EricWiener/liwc-analysis#7]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-9-236181de1062> in <module>
----> 1 LIWC = liwcanalysis.liwc('/Users/lawrencexu/Documents/programming/pro_misinfor/LIWC2015.dic')

~/Library/Python/3.7/lib/python/site-packages/liwcanalysis/liwcanalysis.py in __init__(self, liwc_file_path)
     19         for line in f:
     20             text = line.split(" ,")[0]
---> 21             category = line.split(" ,")[1][:-1]  # remove the "\n"
     22             LIWC_categories.add(category)
     23             if "*" in line:

IndexError: list index out of range

**Comment by EricWiener** [comment]
Could you please post a short excerpt of what your LIWC dictionary looks like.

**Comment by EricWiener** [comment]
I've seen this same error on someone using an improperly formatted dictionary. Please ensure your dictionary is of the form: 
word ,category

Closing this issue
